openapi: 3.0.0
info:
  title: Events
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /events:
    get:
      summary: List Events
      tags:
        - Events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/EventDetail.v1.yaml
              examples: {}
      operationId: get-events
      parameters:
        - schema:
            type: integer
          in: query
          name: title
        - schema:
            type: integer
          in: query
          name: platform
        - schema:
            type: integer
          in: query
          name: organizer
        - schema:
            type: integer
          in: query
          name: status
        - schema:
            type: string
          in: query
          name: name
    post:
      summary: Create Event
      tags:
        - Events
      responses: {}
      operationId: post-events
components:
  schemas: {}
  examples: {}
