openapi: 3.0.0
info:
  title: Titles
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /titles:
    get:
      summary: List Titles
      tags:
        - Titles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Title.v1.yaml
                readOnly: true
              examples: {}
      operationId: get-titles
    post:
      summary: Create Title
      tags:
        - Titles
      responses: {}
      operationId: post-titles
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Title.v1.yaml
            examples:
              example-1:
                value:
                  id: 3
                  name: Rocket League
                  short_name: RL
                  genre: SPR
                  icon: 'https://storage.googleapis.com/lvl-gg-media/titles/3/icon/icon.png'
                  card_background: 'https://storage.googleapis.com/lvl-gg-media/titles/3/cardbg/card_background.png'
                  banner: 'https://storage.googleapis.com/lvl-gg-media/titles/3/banner/banner.png'
                  platforms:
                    - 0
  '/titles/{title_id}':
    parameters:
      - $ref: '#/components/parameters/title_id'
    get:
      summary: Retrieve Title
      tags:
        - Titles
      operationId: get-titles-title_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/Title.v1.yaml
                  - type: object
                    properties:
                      game_modes:
                        type: array
                        items:
                          $ref: ../models/TitleGameMode.v1.yaml
                      maps:
                        $ref: ../models/TitleMap.v1.yaml
                      roles:
                        type: array
                        items:
                          allOf:
                            - $ref: ../models/TitleRole.v1.yaml
                            - type: object
                              properties:
                                positions:
                                  type: array
                                  items:
                                    $ref: ../models/TitlePosition.v1.yaml
                                role_statistics:
                                  type: array
                                  items:
                                    $ref: ../models/TitleStatistic.v1.yaml
              examples: {}
      parameters: []
    patch:
      summary: Update Title
      tags:
        - Titles
      responses: {}
      operationId: patch-titles-title_id
    delete:
      summary: Delete Title
      tags:
        - Titles
      responses: {}
      operationId: delete-titles-title_id
components:
  schemas: {}
  examples: {}
  securitySchemes: {}
  responses: {}
  parameters:
    title_id:
      name: title_id
      in: path
      required: true
      schema:
        type: integer
      description: Title ID
