openapi: 3.0.0
info:
  title: Titles
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /titles:
    get:
      summary: List Titles
      tags:
        - Titles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: ../models/Title.v1.yaml
                    - type: object
                      properties:
                        n_events:
                          type: integer
              examples: {}
      operationId: get-titles
    post:
      summary: Create Title
      tags:
        - Titles
      responses: {}
      operationId: post-titles
  '/titles/{title_id}':
    parameters:
      - schema:
          type: string
        name: title_id
        in: path
        required: true
    get:
      summary: Retrieve Title
      tags:
        - Titles
      responses:
        '200':
          $ref: '#/components/responses/RetrieveTitleResponse'
      operationId: get-titles-title_id
    patch:
      summary: Update Title
      tags:
        - Titles
      responses: {}
      operationId: patch-titles-title_id
    delete:
      summary: Delete Title
      tags:
        - Titles
      responses: {}
      operationId: delete-titles-title_id
components:
  schemas: {}
  examples: {}
  securitySchemes: {}
  responses:
    RetrieveTitleResponse:
      description: Example response
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../models/Title.v1.yaml
              - type: object
                properties:
                  platforms:
                    type: array
                    items:
                      $ref: ../models/Platform.v1.yaml
                  game_modes:
                    type: array
                    items:
                      $ref: ../models/TitleGameMode.v1.yaml
                  maps:
                    type: array
                    items:
                      $ref: ../models/TitleMap.v1.yaml
                  roles:
                    type: array
                    items:
                      $ref: ../models/TitleRole.v1.yaml
                  n_events:
                    type: integer
          examples:
            example-1:
              value:
                id: 3
                name: Rocket League
                short_name: RL
                genre: SPR
                icon: 'https://storage.googleapis.com/lvl-gg-media/titles/3/icon/icon.png'
                card_background: 'https://storage.googleapis.com/lvl-gg-media/titles/3/cardbg/card_background.png'
                banner: 'https://storage.googleapis.com/lvl-gg-media/titles/3/banner/banner.png'
                platforms:
                  - id: 1
                    name: PlayStation 5
                    abbreviation: PS5
                    icon: 'https://storage.googleapis.com/lvl-gg-media/platforms/1/ps4.png'
                game_modes:
                  - id: 1
                    name: string
                maps:
                  - id: 1
                    name: string
                roles:
                  - id: 1
                    name: string
                    positions: string
                    role_statistics: string
                n_events: 0
